version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'

  # Dockerfile base images
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Root and Workspace NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
